[project]
name = "practical-deep-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "duckduckgo-search>=8.1.1",
    "fastai>=2.8.8",
    "fastbook>=0.0.29",
    "fastcore>=2.1.19",
    "fastdownload>=0.0.7",
    "ipykernel>=7.3.0",
    "jupyterlab>=4.6.2",
    "notebook>=7.6.1",
    "pillow>=12.3.0",
]
